#!/bin/sh
# Setup permission
opkg install /root/*.ipk --force-reinstall
rm -f /root/*.ipk
chmod -R 755 /lib/*
chmod -R 755 /etc/profile.d/*
chmod 755 /etc/banner
chmod 755 /etc/profile
chown -R root:root .

(echo "root"; sleep 1; echo "root") | passwd > /dev/null

uci set ttyd.@ttyd[0].command='/bin/bash --login'
uci commit ttyd

uci set system.@system[0].hostname='OpenWRT'
uci set system.@system[0].timezone='WIB-7'
uci set system.@system[0].zonename='Asia/Jakarta'
uci commit system

uci del dhcp.lan.ra
uci del dhcp.lan.ra_slaac
uci del dhcp.lan.ra_flags
uci del dhcp.lan.dhcpv6
uci commit dhcp

sed -i 's/option check_signature/# option check_signature/g' /etc/opkg.conf
echo "src/gz antfrgl_wrt https://raw.githubusercontent.com/antifragile0/antfrgl-opkg/main/aarch64_generic" >> /etc/opkg/customfeeds.conf

