#!/bin/sh
RED="\e[1;31m"
BLUE="\e[1;34m"
GREEN="\e[1;32m"
RESET="\e[0m"

echo -e "${RED}──────────────────────────────────────────────────────${RESET}"
echo -e "${GREEN}       ELCOME to OpenWRT Wieless Freedom!       ${RESET}"
echo -e "${RED}──────────────────────────────────────────────────────${RESET}"
echo -e "${GREEN}    Mod by${RESET} : ${RED}antfrgl${RESET}"
echo -e "${RED}──────────────────────────────────────────────────────${RESET}"
