name: Extract Rootfs
on:
  workflow_dispatch:
    inputs:
      rootfs_name:
        description: 'Rootfs Output Name'
        required: true
      link_type:
        description: 'Select Link Type'
        required: true
        default: 'Wget'
        type: choice
        options:
          - Wget
          - GDrive
      fw_link:
        description: 'Insert firmware link'
        required: true

jobs:
  download:
    name: Download Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Environment
        run: |
          sudo apt update > /dev/null 2>&1
          sudo apt install -y python3 python3-pip > /dev/null 2>&1
          pip3 install gdown > /dev/null 2>&1
          mkdir -p downloads
        
      - name: Download FW
        run: |
          if [ "${{ github.event.inputs.link_type }}" == "Wget" ]; then
            wget "${{ github.event.inputs.fw_link }}"
          elif [ "${{ github.event.inputs.link_type }}" == "GDrive" ]; then
            gdown https://drive.google.com/uc?id=${{ github.event.inputs.fw_link }}
          else
            echo "Error: Unsupported rootfs_type selected."
            exit 1
          fi
          FW_PATH=$(find ./ -name "*img.*")
          echo "FW_PATH=$FW_PATH" >> $GITHUB_ENV

      - name: Extract Fw
        id: extract_fw
        run: |
          if [[ -z "${{ env.FW_PATH }}" ]]; then
              echo "Firmware path is empty. Exiting."
              exit 1
          fi

          if [[ "${{ env.FW_PATH }}" == *.img.gz ]]; then
              sudo gunzip "${{ env.FW_PATH }}"
              rm -rf ${{ env.FW_PATH }}
          elif [[ "${{ env.FW_PATH }}" == *.img.xz ]]; then
              sudo unxz "${{ env.FW_PATH }}"
              rm -rf ${{ env.FW_PATH }}
          else
              echo "Unsupported file type: ${{ env.FW_PATH }}"
              exit 1
          fi

          EXTRACTED_FW=$(find -name "*.img")
          echo "EXTRACTED_FW=${EXTRACTED_FW}" >> $GITHUB_ENV

      - name: Get Partition Offset
        id: get_offset
        run: |
          fdisk_output=$(fdisk -l "${{ env.EXTRACTED_FW }}")
          echo "$fdisk_output"
          offset=$(echo "$fdisk_output" | grep "${{ env.EXTRACTED_FW }}2" | awk '{print $2}')
          partisi_offset=$((offset * 512))
          echo "partisi_offset=$partisi_offset" >> $GITHUB_ENV

      - name: Mount Image
        run: |
          sudo mkdir -p /mnt/openwrt-rootfs
          sudo mount -o loop,offset=${{ env.partisi_offset }} "${{ env.EXTRACTED_FW }}" /mnt/openwrt-rootfs

      - name: Copy Rootfs
        run: |
          mkdir -p extracted-rootfs
          sudo cp -a /mnt/openwrt-rootfs/. /extracted-rootfs/ > /dev/null 2>&1

      - name: Compress Rootfs
        run: |
          sudo tar -czvf ${{ github.event.inputs.rootfs_name }}_rootfs.tar.gz -C /extracted-rootfs/ . > /dev/null 2>&1

      - name: Umount Rootfs
        run: |
          sudo umount /mnt/openwrt-rootfs

      - name: Upload Rootfs
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          name: Mutiara-Wrt Rootfs
          tag_name: all
          draft: false
          prerelease: false
          files: ./*.tar.gz
          body: |
              Kumpulan Rootfs
